### ISSUE TITLE
Problem with complex xpath expressions

### ISSUE THREAD

**Issue by sonofmun** [Capitains/inventory-maker#13]
I tried to ingest the texts from CSEL into my local copy of canonical Latin Lit and it appears that the inventory maker has shortened the xpath expressions right before the "and".  So, an example: on Phaistos (you should have access through your account on Homer, just look for the phaistos directory in your home directory) scans/Data Entry/Jouve/GitHub/csel-dev/split/data/stoa0040/stoa029/stoa0040.stoa029.opp-lat1.xml, we see

```
replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='$1' and @subtype='section'])"
```

But when I ingest this text and check out the <ti:citationMapping><ti:citation>, the xpath is

```
xpath="/tei:div[@n='?'"
```

So it appears to have cut the xpath expression from the document at the space and only taken the first part.  Thus, of course, this does not work when trying a GetPassage on this work.

**Comment by PonteIneptique** [comment]
- [RegExp used in MyCapytain](https://github.com/Capitains/MyCapytain/blob/master/MyCapytain/common/reference.py#L19-L22) ( I think REFSDECL_SPLITTER is the right one )
- [RegExp in Inventory Maker](https://github.com/Capitains/inventory-maker/blob/master/modules/cts.xql#L135)

**Comment by sonofmun** [comment]
The problem in Inventory Maker is fixed.  Now

```
replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='$1' and @subtype='section'])"
```

produces in the inventory 

```
xpath="/tei:div[@n='?' and @subtype='section']"
```

Now the problem seems to be with the CTS API.  When I do the following 

```
http://localhost:8080/exist/restxq/cts?request=GetPassage&inv=latin&urn=urn:cts:latinLit:stoa0040.stoa029.opp-lat1:1
```

I get the following error in CTS 5 API XQ

```
Unsupported Xpath: /tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='1'
```

**Comment by PonteIneptique** [comment]
Never close an issue before the PR is merged :)
